# Generated by Django 6.0.7 on 2026-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
    ]
